version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    environment:
      - API_KEY=${GPT_API_KEY}
      - EMAIL_PASSWORD=${GET_EMAIL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network
    links:
      - code
      - redis
    depends_on:
      - code
      - redis

  code:
    build:
      context: ./code
    ports:
      - "7000:7000"
    networks:
      - app-network

  terminal:
    build:
      context: ./terminal
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network
    command: redis-server --requirepass 1234

networks:
  app-network:
    driver: bridge
